### ISSUE TITLE
Building Jekyll doesn't like the Readme.md

### ISSUE THREAD

**Issue by claytron5000** [juliangruber/balanced-match#22]
When attempting to build a Jekyll site on Github, I'm getting this error:
I'm getting this error ```Your site is having problems building: The variable {{a} on line 50 in node_modules/balanced-match/README.md was not properly closed with }}. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/.```

**Comment by claytron5000** [comment]
:palm: :face: I was not ignoring the `node_modules` directory. PR could still be merged in, but not nearly urgent.

**Comment by keyolk** [comment]
I got same problem : (

**Comment by juliangruber** [comment]
@keyolk hey, why do you need to build this README using jekyll?

**Comment by claytron5000** [comment]
@keyolk Add `/node_modules` to your `.gitignore`. My understanding is that the syntax check is occurring before the build process, so the balanced-match directory (and thus the README) won't be run through whatever syntax checker is finding the error. That said, I *think* my PR would fix this problem if users forget to `gitignore` the `node_modules` directory.

**Comment by TommyJackson85** [comment]
I fixed it adding node_modules/* as-well (I referenced it above). 
Just for further notice, if node_modules has already been uploaded to the repository, adding node_modules/* to .gitignore wont be enough. You will need to untrack node_modules from the repository using the following command: `git rm --cached node_modules -r` :)

**Comment by cortehz** [comment]
@TommyJackson85 I added gitignore, also untracked node_modules from my repo but I still get the same page build error. Why so?

**Comment by TommyJackson85** [comment]
did you add the following to your gitIgnore file?
```
node_modules/*
.idea/
```
Try running
'git rm --cached node_modules -r'   first
and then add the gitignore file, then update your repository

Maybe use this help document. 
https://help.github.com/articles/ignoring-files/

This method is what I used add the gitignore file and untrack the previously committed node_modules. When i ran 'git rm --cached FILENAME' command (file name being node_modules) it prompted me to include '-r'.

**Comment by cortehz** [comment]
Thanks, @TommyJackson85 I finally got it to work.

**Comment by juliangruber** [comment]
I'm going to close this now, thank's everyone for figuring it out!

**Comment by bhagwatn2021** [comment]
@TommyJackson85  I tried your advice. It is updating the build to Github but somehow it is not showing changes on my GitHub page.

**Comment by KnowledgeableKangaroo** [comment]
I am still having this problem - the exact same problem said in the beginning. 
My repository where the problem is can be found here: https://github.com/KnowledgeableKangaroo/supreme-guacamole

I have the node_modules folder in the Codecademy subdirectory. So, I ignored `Codecademy/node_modules/*` in my `.gitignore`. I then listed all ignored files in git bash locally and it showed exactly what I expected. However, I still get these emails and in settings it still shows

>  Your site is having problems building: The variable {{a} on line 50 in Codecademy/node_modules/balanced-match/README.md was not properly closed with }}. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/.

**Comment by claytron5000** [comment]
@KnowledgeableKangaroo Are you building master or your tagged v1.1.4 branch? I ask because I noticed you don't have the node_modules directory in master, but it is in the v1.1.4 branch.

**Comment by ccsalison** [comment]
I had the same issue and I deleted my `node_modules` directory after figuring out that I don't need it anyway.

**Comment by htshon** [comment]
Hello dude , Your site is having problems building: The variable {{a} on line 50 in node_modules/balanced-match/README.md was not properly closed with }}. For more information, see https://help.github.com/articles/page-build-failed-tag-not-properly-terminated/


This is showing to me also how I can fix it .
I have completed the project but this is final stage where I am stucked .
I have to submit it to my college 

Reply as soon as possible
